repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/hakancelikdev/unimport
    rev: 33ead41ee30f1d323a9c2fcfd0114297efbbc4d5
    hooks:
    -   id: unimport
        args: ["--remove"]  # remove after https://github.com/hakancelikdev/unimport/pull/270
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py311-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
-   repo: https://github.com/mxr/unkey
    rev: v0.0.1
    hooks:
    -   id: unkey
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear==22.7.1
        -   flake8-builtins==2.0.1
        -   flake8-comprehensions==3.10.1
        -   flake8-simplify==0.19.3
        -   flake8-typing-imports==1.14.0
-   repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
    -   id: yesqa
        additional_dependencies:
        -   flake8==6.0.0
        -   flake8-bugbear==22.7.1
        -   flake8-builtins==2.0.1
        -   flake8-comprehensions==3.10.1
        -   flake8-simplify==0.19.3
        -   flake8-typing-imports==1.14.0
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
